// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shipping.Data;

#nullable disable

namespace Shipping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Shipping.Models.CauTrucGiaCuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<decimal>("GiaTangThem")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<decimal>("GiaVuot")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<int>("LoaiDichVuId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiVungGia")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianGiao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiDichVuId");

                    b.ToTable("CauTrucGiaCuocs");
                });

            modelBuilder.Entity("Shipping.Models.ChiNhanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongXaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhThanhId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("PhuongXaId");

                    b.HasIndex("TinhThanhId");

                    b.ToTable("ChiNhanhs");
                });

            modelBuilder.Entity("Shipping.Models.ChuyenHang", b =>
                {
                    b.Property<string>("DonHangId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongGuiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhuongNhanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ShipperId")
                        .HasColumnType("int");

                    b.Property<string>("TinhGuiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TinhNhanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DonHangId", "ThuTu");

                    b.HasIndex("PhuongGuiId");

                    b.HasIndex("PhuongNhanId");

                    b.HasIndex("ShipperId");

                    b.HasIndex("TinhGuiId");

                    b.HasIndex("TinhNhanId");

                    b.ToTable("ChuyenHangs");
                });

            modelBuilder.Entity("Shipping.Models.Config", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<int>("LoaiGiaTri")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("Shipping.Models.DonHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("COD")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<string>("ChiTietPhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ChieuCao")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("ChieuDai")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("ChieuRong")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("DiaChiGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhGoiHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhXacNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiDichVuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("PTThanhToan")
                        .HasColumnType("int");

                    b.Property<decimal>("PhiGiaoHang")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<string>("PhuongGuiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhuongNhanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TTNguoiGui")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TTNguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<string>("TinhGuiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TinhNhanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TongPhiPhuTro")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<int>("TrangThaiDH")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiTT")
                        .HasColumnType("int");

                    b.Property<decimal>("TrongLuongQuyDoi")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("TrongLuongThuc")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("LoaiDichVuId");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("PhuongGuiId");

                    b.HasIndex("PhuongNhanId");

                    b.HasIndex("TinhGuiId");

                    b.HasIndex("TinhNhanId");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("Shipping.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongXaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhThanhId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.HasIndex("PhuongXaId");

                    b.HasIndex("TinhThanhId");

                    b.HasIndex("UserId");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("Shipping.Models.LoaiDichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonViTangThem")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("MaDV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MocCanNang")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThoiGianToiDa")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianToiThieu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaDV")
                        .IsUnique();

                    b.ToTable("LoaiDichVus");
                });

            modelBuilder.Entity("Shipping.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ChiNhanhId")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQuanLy")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("PhuongXaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhThanhId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.HasIndex("ChiNhanhId");

                    b.HasIndex("PhuongXaId");

                    b.HasIndex("TinhThanhId");

                    b.HasIndex("UserId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("Shipping.Models.PhuongXa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenPhuongXa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhThanhId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("TinhThanhId");

                    b.ToTable("PhuongXas");
                });

            modelBuilder.Entity("Shipping.Models.Shipper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ChiNhanhId")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiShipper")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("PhuongXaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhThanhId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.HasIndex("ChiNhanhId");

                    b.HasIndex("PhuongXaId");

                    b.HasIndex("TinhThanhId");

                    b.HasIndex("UserId");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("Shipping.Models.TinhThanh", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VungMienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VungMienId");

                    b.ToTable("TinhThanhs");
                });

            modelBuilder.Entity("Shipping.Models.VungMien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenVungMien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("VungMiens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shipping.Models.CauTrucGiaCuoc", b =>
                {
                    b.HasOne("Shipping.Models.LoaiDichVu", "LoaiDichVu")
                        .WithMany("CauTrucGiaCuocs")
                        .HasForeignKey("LoaiDichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiDichVu");
                });

            modelBuilder.Entity("Shipping.Models.ChiNhanh", b =>
                {
                    b.HasOne("Shipping.Models.PhuongXa", "PhuongXa")
                        .WithMany("ChiNhanhs")
                        .HasForeignKey("PhuongXaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.TinhThanh", "TinhThanh")
                        .WithMany("ChiNhanhs")
                        .HasForeignKey("TinhThanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhuongXa");

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("Shipping.Models.ChuyenHang", b =>
                {
                    b.HasOne("Shipping.Models.DonHang", "DonHang")
                        .WithMany("ChuyenHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.PhuongXa", "PhuongXaGui")
                        .WithMany("GuiChuyenHangs")
                        .HasForeignKey("PhuongGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.PhuongXa", "PhuongXaNhan")
                        .WithMany("NhanChuyenHangs")
                        .HasForeignKey("PhuongNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.Shipper", "Shipper")
                        .WithMany("ChuyenHangs")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shipping.Models.TinhThanh", "TinhThanhGui")
                        .WithMany("GuiChuyenHangs")
                        .HasForeignKey("TinhGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.TinhThanh", "TinhThanhNhan")
                        .WithMany("NhanChuyenHangs")
                        .HasForeignKey("TinhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("PhuongXaGui");

                    b.Navigation("PhuongXaNhan");

                    b.Navigation("Shipper");

                    b.Navigation("TinhThanhGui");

                    b.Navigation("TinhThanhNhan");
                });

            modelBuilder.Entity("Shipping.Models.DonHang", b =>
                {
                    b.HasOne("Shipping.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shipping.Models.LoaiDichVu", "LoaiDichVu")
                        .WithMany("DonHangs")
                        .HasForeignKey("LoaiDichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.NhanVien", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shipping.Models.PhuongXa", "PhuongXaGui")
                        .WithMany("GuiDonHangs")
                        .HasForeignKey("PhuongGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.PhuongXa", "PhuongXaNhan")
                        .WithMany("NhanDonHangs")
                        .HasForeignKey("PhuongNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.TinhThanh", "TinhThanhGui")
                        .WithMany("GuiDonHangs")
                        .HasForeignKey("TinhGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.TinhThanh", "TinhThanhNhan")
                        .WithMany("NhanDonHangs")
                        .HasForeignKey("TinhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("LoaiDichVu");

                    b.Navigation("NhanVien");

                    b.Navigation("PhuongXaGui");

                    b.Navigation("PhuongXaNhan");

                    b.Navigation("TinhThanhGui");

                    b.Navigation("TinhThanhNhan");
                });

            modelBuilder.Entity("Shipping.Models.KhachHang", b =>
                {
                    b.HasOne("Shipping.Models.PhuongXa", "PhuongXa")
                        .WithMany("KhachHangs")
                        .HasForeignKey("PhuongXaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.TinhThanh", "TinhThanh")
                        .WithMany("KhachHangs")
                        .HasForeignKey("TinhThanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhuongXa");

                    b.Navigation("TinhThanh");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shipping.Models.NhanVien", b =>
                {
                    b.HasOne("Shipping.Models.ChiNhanh", "ChiNhanh")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChiNhanhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shipping.Models.PhuongXa", "PhuongXa")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhuongXaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.TinhThanh", "TinhThanh")
                        .WithMany("NhanViens")
                        .HasForeignKey("TinhThanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("PhuongXa");

                    b.Navigation("TinhThanh");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shipping.Models.PhuongXa", b =>
                {
                    b.HasOne("Shipping.Models.TinhThanh", "TinhThanh")
                        .WithMany("PhuongXas")
                        .HasForeignKey("TinhThanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("Shipping.Models.Shipper", b =>
                {
                    b.HasOne("Shipping.Models.ChiNhanh", "ChiNhanh")
                        .WithMany("Shippers")
                        .HasForeignKey("ChiNhanhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shipping.Models.PhuongXa", "PhuongXa")
                        .WithMany("Shippers")
                        .HasForeignKey("PhuongXaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipping.Models.TinhThanh", "TinhThanh")
                        .WithMany("Shippers")
                        .HasForeignKey("TinhThanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("PhuongXa");

                    b.Navigation("TinhThanh");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shipping.Models.TinhThanh", b =>
                {
                    b.HasOne("Shipping.Models.VungMien", "VungMien")
                        .WithMany("TinhThanhs")
                        .HasForeignKey("VungMienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VungMien");
                });

            modelBuilder.Entity("Shipping.Models.ChiNhanh", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("Shippers");
                });

            modelBuilder.Entity("Shipping.Models.DonHang", b =>
                {
                    b.Navigation("ChuyenHangs");
                });

            modelBuilder.Entity("Shipping.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("Shipping.Models.LoaiDichVu", b =>
                {
                    b.Navigation("CauTrucGiaCuocs");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("Shipping.Models.NhanVien", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("Shipping.Models.PhuongXa", b =>
                {
                    b.Navigation("ChiNhanhs");

                    b.Navigation("GuiChuyenHangs");

                    b.Navigation("GuiDonHangs");

                    b.Navigation("KhachHangs");

                    b.Navigation("NhanChuyenHangs");

                    b.Navigation("NhanDonHangs");

                    b.Navigation("NhanViens");

                    b.Navigation("Shippers");
                });

            modelBuilder.Entity("Shipping.Models.Shipper", b =>
                {
                    b.Navigation("ChuyenHangs");
                });

            modelBuilder.Entity("Shipping.Models.TinhThanh", b =>
                {
                    b.Navigation("ChiNhanhs");

                    b.Navigation("GuiChuyenHangs");

                    b.Navigation("GuiDonHangs");

                    b.Navigation("KhachHangs");

                    b.Navigation("NhanChuyenHangs");

                    b.Navigation("NhanDonHangs");

                    b.Navigation("NhanViens");

                    b.Navigation("PhuongXas");

                    b.Navigation("Shippers");
                });

            modelBuilder.Entity("Shipping.Models.VungMien", b =>
                {
                    b.Navigation("TinhThanhs");
                });
#pragma warning restore 612, 618
        }
    }
}
